"""Add soft delete

Revision ID: 37bf6b7af6e5
Revises: a4929a255e81
Create Date: 2026-06-01 23:21:12.287771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37bf6b7af6e5'
down_revision: Union[str, None] = 'a4929a255e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('calendar_events', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'updated_at')
    op.drop_column('calendar_events', 'is_deleted')
    # ### end Alembic commands ###
