"""Add is_notified to CalendarEvent

Revision ID: 9e421281dc84
Revises: aa270ed80718
Create Date: 2026-06-05 19:40:13.255371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e421281dc84'
down_revision: Union[str, Sequence[str], None] = 'aa270ed80718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('is_notified', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'is_notified')
    # ### end Alembic commands ###
