"""Add deadline to tasks

Revision ID: ca24e1a79b82
Revises: 9e421281dc84
Create Date: 2026-06-15 12:20:38.140286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca24e1a79b82'
down_revision: Union[str, Sequence[str], None] = '9e421281dc84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.String(length=20), nullable=False))
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('tasks', sa.Column('is_notified', sa.Boolean(), server_default='0', nullable=False))
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.DATETIME(), nullable=True))
    op.drop_column('tasks', 'is_notified')
    op.drop_column('tasks', 'is_deleted')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'deadline')
    # ### end Alembic commands ###
